# Generated by Django 4.0.4 on 2022-08-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ellie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
