# Generated by Django 4.0.4 on 2022-08-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ellie', '0002_fact_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='image_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
