# Generated by Django 4.0.4 on 2022-08-22 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ellie', '0003_fact_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fact',
            name='image_name',
        ),
    ]
